defaults:
  - _self_
  - audio: byol
  - vision: timesformer
  - text: bert

name: avt-timesformer-byol-bert

model_dir: ./models
checkpoint: null
modalities: ["a", "v", "t"]

# ################ projection network #############
head_type: mlp
proj_embedding_dim: 2048

# ################ loss and optimizer #################
use_gradnorm: true
learning_rate: 5e-5
batch_size: 64
milestones: [20, 40, 80, 100]
gamma: 0.5